name: Deploy to Azure VM

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Write private key to file
      run: |
        echo "-----BEGIN RSA PRIVATE KEY-----
        MIIG4wIBAAKCAYEA1YB4IJt8RMgL5NxzDJdqG3UgBMr+qS6V1Gpi9xUVhhFkCyj0
        gnr1vgH9B7cbAcf+RjIqEk4o+UPyUxtudzstd51M9Az3JOunEGoI4SDZRZdD1YVM
        x5/qr8y6jnZabvS40P6oh7w1XzdStGhZIyuo8O5m5dpmBcvv+V4NzC7LujXXb0eq
        1047PgqJMjzdS+1mYOlvOuFBv3YVoB4tofPH8ltqIdgQ/ReIA0Mz5fkeNkK0Zy0L
        5mAL2Mz3GZ72AeaA3Q28W8bzrz0gPDTeP9w/3TYilyFiEAwPa4Pe0DKlxfiiHZsB
        ZzoEwqPUMEHzVwaugCZqJ/wE3jYoTKO+UehSqNysf7GNX/fWrBfCx2nPTRFc1/bE
        K9rieIusi7Y+FifrxIt9toT9clwzB7B1gnGmgciq+ZXLrnhu1QTWw1IXltU0bEW6
        oqtqucgbLeecgUts1rqh9jV5SYSaxU2Y/xfWL++6wvz3GVTAghy2n5gHXmXuz1xi
        BF9RgECC7auDoGAtAgMBAAECggGBAIqTymUPxwc1+VJhLGPd28darJ+vyr+xNxsa
        uoW5r7DHlPIRcTNH8D2WONBLL0Jmt0qEwP4EsV+plJ4QzhCh3o8nEI3P5JKYSmXD
        DWRi1+PtnN/4l69ywve8oNJbS7N9MICm6mi/5ryYwhvLJyBG9G79rtg+e74Dcw2e
        2MHRFfcVf3IBSIhbhORuHkL3coQX4T3CBqpnDy/gy4SUUfYur3dFkovJHK3KGkRT
        2FnK6qs5fLMDcBfl+4qK71A392GgZJCVBV3fVukgREVR+akB3auR80T+moMlpOuu
        dbh+vDvn/bU7Rg96ryI3mU4QMEWHKTMYL4VFuYiu5RENX2rMfOxePCm1cGqr1l5q
        NQ9HsQdw2nApbjTHyFfcknlK/YhbdltoaUeSGqwwJ1ujBY7/WG+nWXpkow1becQK
        u2Jx3NL3hN96FYDfIdZEIiWvuYnuljYbq1qjroA8coxoBfEarTBRGV98RJSnbdJQ
        k4pfoCJDTyJzGEF8ai/WU+yQJ/KwWQKBwQDnkuCDs7fwPJyUNvKKrL96pHc4he5M
        unQw7Oha3WVXnV0iuCZPKkoj2DaDfFAhZRDl7+aj49cGoOG+nP/LWhE9R+HU71T3
        /3/UsGR+6bt8g6wwibS3+hE9OVJrCQj2z0pzOojbOqah6onTgTh+94i/ieGv3iH1
        FE3MaTI2kWp7zBGGgrdqG5dvbESZsr3+IxJUH2XcaTdk7IuAsg9Livy1w8/MVWhI
        gbL8bmHupuKtk1Ra/q8nP9hz+ssHY0iwXCcCgcEA7AWZ+d5p1I1LYIG/lryQFXFV
        ucJFsIRjGHuJHWe2AoKL1JGXTRCXh3DH5ncM8CMcGjLWxjn1yWCwxoKSInyKL8D8
        Wms1jYipAv7ro/vSGgkou+mfLULk8wazsMdC2QYwcrNG3z3zyjRHUFv1QMjTMy7h
        KFDmgey44u5uj1hQWVJLPLffg/o40fvh4dE8xUjHSkDPLrXygIS8leW0Fh+ttRA8
        eEN2sH6wA4SgPL+ijhCwr+JVnXV8dviUREj/WlGLAoHAIkVvaq5XQ3uE5L55CKLm
        N51Nc5UGnl5dwbvd60ymqd/FH9VG/iJRFJrz/mOQbFDLvmvRo2GdugJnRlFv3cV3
        la0ks+Gznnw2i+CLDulCcPv/qLNIho3ArWHlW6fbpsMozoLULDWy4XWXbjDKjqfN
        miMqvl9OgTm/BchvwPmmW6no0hJYWKC6uae5Q1HbolfIZ6C573O22f3T63juoIxy
        N+hBwYjGRSzEs20Wmz4hf/S04D6e510giJGOKIq+ADOzAoHAJjbF9mnncq2p3adE
        UPCY14/xFFF7HRhiPw2JZsRq+L8QSsuD1stv7VL6Wrs90getPiSrF488120bUhjD
        9md5rD+v3CftlMviqYSCvJtCKkr/WGV8C0UAcsTMBTxN+3uADqIuQGj0dvG99ind
        bK7XWzsk43UtzS15xexa5ESlRcEIQ3116BV0a7M/oGNTVpHxCnmx0dtNtzdGnXKC
        lO5uHpnRYJtztSHd98PaeduBQ0U6hk+8EvF5xH187A1xorr/AoHAYPMlAaVROtJl
        KMLceXO8fe2x+HslDKykAMNLd9NLjFsS0BlEkEBQ70JGs/9f2rEDR8nu7o6dsIr0
        LOYLn9AIfE/uuo/Ua6G+RjnFPfOwoz80KdYUhr9lCu6qOGA+Akvgu8GxtET7Isil
        ajjZTP/wYO5cc9wiDaSNjmLz7BOMpdLe6Djh/57iWG3PElgxZla5fJ1yF1vx+JFL
        NeoUfAjzXS7zcaB47emFA0q9s97zOfkr56xF4IqegmUhdtAAfDPu
        -----END RSA PRIVATE KEY-----" > private_key
        chmod 600 private_key

    - name: Copy code to VM via SCP
      run: |
        scp -i private_key -o StrictHostKeyChecking=no -r . soma@52.249.217.156:/home/soma/soma-voice-translator

    - name: SSH and deploy app
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no soma@52.249.217.156 << 'EOF'
          cd /home/soma/soma-voice-translator
          sudo apt update
          sudo apt install -y python3-pip nodejs npm unzip
          
          # Install frontend dependencies
          cd client
          npm install

          # Install backend dependencies
          cd ../server
          pip3 install -r requirements.txt

          # Stop any existing processes
          pkill -f node || true
          pkill -f python || true

          # Start backend
          nohup python3 app.py > app.log 2>&1 &

          # Serve frontend
          cd ../client
          nohup npx serve -l 3000 . > client.log 2>&1 &
        EOF
