name: Deploy to Azure VM

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Write private key to file
      run: |
        echo "-----BEGIN RSA PRIVATE KEY-----
        MIIG4wIBAAKCAYEApmS06dNZSQpOMrPya0fcJO1xHgtKkU1M2TnJblgUv0TTm63v
        ICWyuOurLa2PWs/LaIjQBkxQZM0G1Pi3IGpbvWkLeXZeDt8viEzVy9iHNn37jxbF
        II7sYR9ep+CnWs+LSdeO735b95kZWuWSECb9m8oehsX2K5j23Xe5QG+kmPXKuFz5
        2uRusHpyWEOMKZHuNo1qx3+PKGWqUQYr92BBqsbZlimQxidjvqhtjWKSg0aKjJhF
        ydbIO3bxqQzk9Q8fQRmfAich+B8iXX5SegEKcMyfkM4LN0oUcSeUaYf/WMCgILC4
        +S+aEWDS1pCUnytcK7GnrABpq6nWhX4UQgEBgUJ+gAP6r+T23cAcy3x0Md1Gyb/o
        RzMFd5vnEPF1JrWK3AJ3KJoG/X1FRcd6mhKVF5gZqenpBG6YZgy3KN+F3q9fdOOP
        8oS5X4XhJsLzsv3h/BOj0f7MolMbmUpdZnJ0gxJh9MHPmhdsEkopON0okRutk3jd
        /pu2fB6VKre8TQvdAgMBAAECggGAUGMq/CR9aEowSVKida3772M/WRJ/bf94dyHx
        7Ptk2ps32GiJtHBCDhDdXG4Taf4l+VTPm5tW47wh5tZaMrDvrWyIfJ/xBSJSZnko
        eRkdCfiHhjOr/PTPwoRTSKvCbp8CXiRkC9RyPgabN0zd6ivMLm3Rna8aJSn7ajej
        KjxFuxhUXgmdNGFUELK3d2j62EKGYZik08kOsqebRxXCO/sm/oifKmreZL029S+N
        7daHjiCQYyhV3xODHSdzzQZLvxEUcwStXDfu8vpv8ML1RdE9yti0Gff9BItY7qDH
        TYs8zZBWG52aRs1h7FPAtE6Zdv0pBPjswabKdzN9nr0pbHIz6qP3vEz3xlmGC9QD
        8bou2UqvI4DxazMYlp3wk01zOajR8d+NlIId4Nqc5wfhuKy5qzYkBoF1pX9JLppH
        brWCNOOOE/3rsxXx41bMYMFHjxM+9cBGqJd8X4kZXX2QMcuYEMw/d7G7UfT1KIx8
        s1411oObklyS5d0R+PjK1GjrWlkJAoHBAM57c2xj9pK0rnfdNGcYPEAqFYqi/+Ne
        xpAVNhMOvCGVe+rLnmtQfyRBKvoKJRQ/y1QLQZhRuoZG3zHxNbKnNPeN/UY9mHF7
        IFZQU5KJAN3CaUZgueVJlrbowDU2Kd05Op7QeTn2PChzxA0Pyf2kFr5Re3rtV0iJ
        UxeX3um+p/7oLmEiA8PWP+2UwKH2y6ndm7hBrEHe9b4PYHy8wdSm0l9AvPPOXY8y
        Q2MS8oxV8jBknGS8eCBMmzzAKb1pIBFwCwKBwQDOTBWNmhHvma4icMQ4/Muy72x1
        W50Fvx0Xkdfwi3OwaHKXPtpBe77y9sR/2xuemFGENYdaC5F9JVlFZP2o2ut/iNtT
        xZthejdAeoqcdw9daCymzSa/qn9g7popi5okocjNjl0tf4jEP3PZ5tqibWhGrlPT
        MGlhTJi/rC5Q2A7u4jBq9xd0DqJhEfjjQQELg0m7zCyxd6e+2X9jU0QXNM80bH54
        Gppb4FS82bx463Yukuy3t7bhbiO4f4XbRUP2XLcCgcEAh2A5FN+VUipUGRJWwSEK
        n6b36KVlz9Tbqqu9gFEw13QCgrZtbz6fnU18t+Le3J/W14tpvkwXVuIwg7X51t/5
        wjS90cegowZu9ShFItXgU4SbMSFJwCK3RcTj//87A2f6HxXf5TijyIHeEBJCBKII
        p08U/kuN5mjiqZ1Q8T+nNWFUxypd/ZAC6emVQptkfEJnTi8AmU9tHudGA4JeMuYN
        F5aCS/cJMFFsDRDnJUtUNpZAU2ud9s9DGFmFBEJgXA5xAoHAfdFFa+FFgx31aCfi
        ZOc4zN7dBQ5ky/ZtJczbKGfEnRh2muvIbRutr7z0xw244JcBUGLdM/vONccrlPkt
        A2jRLC0ppwPj6iWBwR97nkW25z77zJdeRJMVsOaUuzXbQvAw6b0j8vXPUfFpFMKJ
        IXscl88GbM0f2CnBF1VJwiCjqunkobglY7DxM8akRuWEX6MouxKhR3M0qV85JDjK
        VGTu4ogw8cs3zUUaKTuaiR0CLRGKsdmn/gEQZBvSZZLvCjgtAoHAClCNbMVpAH/A
        ftvaskS0SxC40el5mqzQFjO4FRLjiLeGD+oK3m3h8fH+iQJ+DapiZXFj3daKWDSC
        ss9tuLNrmwroNP2dC1dPgVtcuYnVzSCdFG6ktdpiUuRhLEt6m9HTCmf/mrKZHrr/
        LYi4Fe6VYL1oVzCZI6Xt/pX2tY2mb6vayHkmhCWfi4dbtA/TQ9sWBLZcgmmGKnSh
        swpLu9x6byjHmWGrHzwNHQHntvZyHx1Be2WKC36t2pchlYsbuau8
        -----END RSA PRIVATE KEY-----" > private_key
        chmod 600 private_key

    - name: Copy code to VM via SCP
      run: |
        scp -i private_key -o StrictHostKeyChecking=no -r . soma@20.83.173.209:/home/soma/soma-voice-translator

    - name: SSH and deploy app
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no soma@20.83.173.209 << 'EOF'
          cd /home/soma/soma-voice-translator
          sudo apt update
          sudo apt install -y python3-pip nodejs npm unzip
          
          # Install frontend dependencies
          cd client
          npm install

          # Install backend dependencies
          cd ../server
          pip3 install -r requirements.txt

          # Stop any existing processes
          pkill -f node || true
          pkill -f python || true

          # Start backend
          nohup python3 app.py > app.log 2>&1 &

          # Serve frontend
          cd ../client
          nohup npx serve -l 3000 . > client.log 2>&1 &
        EOF
